# Generated by Django 5.1.7 on 2025-03-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciliacionExpedientes',
            fields=[
                ('expediente', models.CharField(db_column='EXPEDIENTE', max_length=255, primary_key=True, serialize=False)),
                ('junta', models.CharField(blank=True, db_column='JUNTA', max_length=255, null=True)),
                ('tomo', models.CharField(blank=True, db_column='TOMO', max_length=255, null=True)),
                ('actor_nombre', models.CharField(blank=True, db_column='ACTOR (NOMBRE)', max_length=255, null=True)),
                ('mujer_numero', models.CharField(blank=True, db_column='MUJER (NUMERO)', max_length=255, null=True)),
                ('hombre_numero', models.CharField(blank=True, db_column='HOMBRE (NUMERO)', max_length=255, null=True)),
                ('demandado_nombre', models.CharField(blank=True, db_column='DEMANDADO (NOMBRE)', max_length=255, null=True)),
                ('mujer_numero_0', models.CharField(blank=True, db_column='MUJER (NUMERO)_[0]', max_length=255, null=True)),
                ('hombre_numero_0', models.CharField(blank=True, db_column='HOMBRE (NUMERO)_[0]', max_length=255, null=True)),
                ('persona_moral_numero', models.CharField(blank=True, db_column='PERSONA MORAL (NUMERO)', max_length=255, null=True)),
                ('iebem', models.CharField(blank=True, db_column='IEBEM', max_length=255, null=True)),
                ('servicios_salud', models.CharField(blank=True, db_column='SERVICIOS SALUD', max_length=255, null=True)),
                ('poder_ejecutivo', models.CharField(blank=True, db_column='PODER EJECUTIVO', max_length=255, null=True)),
                ('ayuntamientos', models.CharField(blank=True, db_column='AYUNTAMIENTOS', max_length=255, null=True)),
                ('otros_organismos', models.CharField(blank=True, db_column='OTROS ORGANISMOS', max_length=255, null=True)),
                ('no_se_ha_notificado_a_las_partes', models.CharField(blank=True, db_column='NO SE HA NOTIFICADO A LAS PARTES', max_length=255, null=True)),
                ('empl_no_realizado', models.CharField(blank=True, db_column='EMPL.NO REALIZADO', max_length=255, null=True)),
                ('empl_exhorto', models.CharField(blank=True, db_column='EMPL. EXHORTO', max_length=255, null=True)),
                ('exhorto_sin_enviar', models.CharField(blank=True, db_column='EXHORTO SIN ENVIAR', max_length=255, null=True)),
                ('exhorto_cdmx', models.CharField(blank=True, db_column='EXHORTO CDMX', max_length=255, null=True)),
                ('exhorto_foraneos', models.CharField(blank=True, db_column='EXHORTO FORANEOS', max_length=255, null=True)),
                ('cde', models.CharField(blank=True, db_column='C.D.E.', max_length=255, null=True)),
                ('tercero_llamado_a_juicio', models.CharField(blank=True, db_column='TERCERO LLAMADO A JUICIO', max_length=255, null=True)),
                ('oap', models.CharField(blank=True, db_column='O.A.P.', max_length=255, null=True)),
                ('desahogo_pruebas', models.CharField(blank=True, db_column='DESAHOGO PRUEBAS', max_length=255, null=True)),
                ('test_falta_citar', models.CharField(blank=True, db_column='TEST. FALTA CITAR', max_length=255, null=True)),
                ('periciales_partes', models.CharField(blank=True, db_column='PERICIALES PARTES', max_length=255, null=True)),
                ('pericial_tercero', models.CharField(blank=True, db_column='PERICIAL TERCERO', max_length=255, null=True)),
                ('inf_falta_hacer', models.CharField(blank=True, db_column='INF. FALTA HACER', max_length=255, null=True)),
                ('inf_falta_desahogar', models.CharField(blank=True, db_column='INF. FALTA DESAHOGAR', max_length=255, null=True)),
                ('otras_pruebas', models.CharField(blank=True, db_column='OTRAS PRUEBAS', max_length=255, null=True)),
                ('alegatos', models.CharField(blank=True, db_column='ALEGATOS', max_length=255, null=True)),
                ('prueba_pendiente', models.CharField(blank=True, db_column='PRUEBA PENDIENTE', max_length=255, null=True)),
                ('cierre', models.CharField(blank=True, db_column='CIERRE', max_length=255, null=True)),
                ('laudo_dictado', models.CharField(blank=True, db_column='LAUDO DICTADO', max_length=255, null=True)),
                ('absolutorio', models.CharField(blank=True, db_column='ABSOLUTORIO', max_length=255, null=True)),
                ('condenatorio', models.CharField(blank=True, db_column='CONDENATORIO', max_length=255, null=True)),
                ('monto', models.CharField(blank=True, db_column='MONTO', max_length=255, null=True)),
                ('auto_ejecucion', models.CharField(blank=True, db_column='AUTO EJECUCCION', max_length=255, null=True)),
                ('terceria', models.CharField(blank=True, db_column='TERCERIA', max_length=255, null=True)),
                ('recurso_revision', models.CharField(blank=True, db_column='RECURSO REVISION', max_length=255, null=True)),
                ('remate', models.CharField(blank=True, db_column='REMATE', max_length=255, null=True)),
                ('inactividad_1_anio', models.CharField(blank=True, db_column='INACTIVIDAD 1 ANIO', max_length=255, null=True)),
                ('inactividad_2_anios_mas', models.CharField(blank=True, db_column='INACTIVIDAD 2 ANIOS MAS', max_length=255, null=True)),
                ('amparo_indirecto', models.CharField(blank=True, db_column='AMPARO INDIRECTO', max_length=255, null=True)),
                ('amparo_directo_cumpl', models.CharField(blank=True, db_column='AMP. DIRECTO CUMPL', max_length=255, null=True)),
                ('sustitucion_patronal', models.CharField(blank=True, db_column='SUSTITUCION PATRONAL', max_length=255, null=True)),
                ('no_interpuesta', models.CharField(blank=True, db_column='NO INTERPUESTA', max_length=255, null=True)),
                ('prescripcion', models.CharField(blank=True, db_column='PRESCRIPCION', max_length=255, null=True)),
                ('depuracion', models.CharField(blank=True, db_column='DEPURACION', max_length=255, null=True)),
                ('regularizar', models.CharField(blank=True, db_column='REGULARIZAR', max_length=255, null=True)),
                ('reviso_y_capturo', models.CharField(blank=True, db_column='REVISO Y CAPTURO', max_length=255, null=True)),
            ],
            options={
                'db_table': 'expedientes',
                'managed': False,
            },
        ),
    ]
