# Generated by Django 5.1.7 on 2025-04-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_conciliacionexpedientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosMilSiete',
            fields=[
                ('id_expediente', models.AutoField(db_column='id_expediente', primary_key=True, serialize=False, unique=True)),
                ('expediente', models.CharField(db_column='EXPEDIENTE', max_length=255)),
                ('junta', models.CharField(blank=True, db_column='JUNTA', max_length=255)),
                ('actor', models.CharField(blank=True, db_column='ACTOR', max_length=255)),
                ('demandado', models.CharField(blank=True, db_column='DEMANDADO', max_length=255)),
                ('no_se_ha_notificao_a_las_partes', models.CharField(blank=True, db_column='NO SE HA NOTIFICACO A LAS PARTES', max_length=255, null=True)),
                ('empl_no_realizado', models.CharField(blank=True, db_column='EMPL NO REALIZADO', max_length=255, null=True)),
                ('empl_exhorto', models.CharField(blank=True, db_column='EMPL. EXHORTO', max_length=255, null=True)),
                ('cde', models.CharField(blank=True, db_column='CDE', max_length=255, null=True)),
                ('oap', models.CharField(blank=True, db_column='OAP', max_length=255, null=True)),
                ('desahogo_pruebas', models.CharField(blank=True, db_column='DESAHOGO PRUEBAS', max_length=255, null=True)),
                ('cierre', models.CharField(blank=True, db_column='CIERRE', max_length=255, null=True)),
                ('laudo_dictado', models.CharField(blank=True, db_column='LAUDO DICTADO', max_length=255, null=True)),
                ('auto_ejecucion', models.CharField(blank=True, db_column='AUTO EJECUCCION', max_length=255, null=True)),
                ('prescripcion', models.CharField(blank=True, db_column='PRESCRIPCION', max_length=255, null=True)),
                ('regularizar', models.CharField(blank=True, db_column='REGULARIZAR', max_length=255, null=True)),
            ],
            options={
                'db_table': 'dosmilsiete',
                'managed': False,
            },
        ),
    ]
