# Generated by Django 5.1.7 on 2025-04-27 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dosmilsiete'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaDescarga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre_carga', models.CharField(max_length=255)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empleado')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dosmilsiete')),
            ],
            options={
                'db_table': 'cargadescarga',
            },
        ),
    ]
