# Generated by Django 5.1.7 on 2025-04-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cargadescarga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivados',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('expediente', models.CharField(max_length=255)),
                ('junta', models.CharField(max_length=255)),
                ('actor', models.CharField(max_length=255)),
                ('demandado', models.CharField(max_length=255)),
                ('fecha_archivo', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField()),
            ],
            options={
                'db_table': 'archivados',
            },
        ),
    ]
