# Generated by Django 5.1.7 on 2026-01-21 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_archivados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.empleado')),
            ],
            options={
                'db_table': 'bitacora',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
